name: unscripted
version: 0.5.2
author: Sean Eagan <seaneagan1@gmail.com>
description: Declarative command-line interface programming.
homepage: http://github.com/seaneagan/unscripted
dependencies:
  ansicolor: any
  args: '>=0.11.0 <0.13.0'
  collection: any
  mockable_filesystem: any
  path: any
  quiver: any
  supports_color: any
dev_dependencies:
  unittest: any
