name: unscripted
author: Sean Eagan <seaneagan1@gmail.com>
version: 0.2.0
homepage: http://github.com/seaneagan/unscripted
description: Write command-line scripts as ordinary methods and classes.
documentation: http://seaneagan.github.com/unscripted
dependencies:
  args: any
  collection: any
  path: any
dev_dependencies:
  unittest: any
