name: unscripted
author: Sean Eagan <seaneagan1@gmail.com>
version: 0.0.2
homepage: http://github.com/seaneagan/unscripted
description: Sketch command-line interfaces using normal programming constructs annotated with command-line specific metadata.
documentation: http://seaneagan.github.com/unscripted
dependencies:
  args: any
dev_dependencies:
  unittest: any
