name: unscripted
author: Sean Eagan <seaneagan1@gmail.com>
version: 0.0.1
homepage: http://github.com/seaneagan/unscripted
description: Design command line interfaces through normal programming interfaces annotated with command line specific metadata.
documentation: http://seaneagan.github.com/unscripted
dependencies:
  args: any
dev_dependencies:
  unittest: any
