name: unscripted
author: Sean Eagan <seaneagan1@gmail.com>
version: 0.3.0
homepage: http://github.com/seaneagan/unscripted
description: Declarative command-line interface programming.
documentation: http://seaneagan.github.com/unscripted
dependencies:
  args: any
  collection: any
  mockable_filesystem: any
  path: any
dev_dependencies:
  quiver: any
  unittest: any
